# Shopify App Configuration (Production)
client_id = "4324b564c91fce32034ad0f1c8b4cba6"
name = "From"
handle = "from-6"
application_url = "https://store.enuid.com"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory,read_locations,read_product_listings,read_orders,read_all_orders,read_checkouts,write_checkouts,read_customers,read_fulfillments,read_shipping,read_analytics,read_discounts,read_price_rules,read_collections,write_orders,read_returns,write_returns"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://store.enuid.com/api/auth/callback/shopify",
  "https://store.enuid.com/api/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
